//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UModule.Database.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstimateLineItem
    {
        public int LineItemID { get; set; }
        public Nullable<int> EstimateID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual Estimate Estimate { get; set; }
        public virtual Product Product { get; set; }
    }
}
