//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UModule.Database.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTransaction
    {
        public int TransactionID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PaymentMethod { get; set; }
        public string TransactionStatus { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
